"""fix sevoil modele

Revision ID: 10803326f097
Revises: 45950d98bf7a
Create Date: 2026-04-15 16:00:00.205993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10803326f097'
down_revision: Union[str, None] = '45950d98bf7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_price_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('purchase_sir_unit', sa.Float(), nullable=False),
    sa.Column('taxes_unit', sa.Float(), nullable=False),
    sa.Column('margin_boss_unit', sa.Float(), nullable=False),
    sa.Column('selling_price_unit', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_price_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_price_configs_id'), ['id'], unique=False)

    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit_purchase_price', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('unit_taxes', sa.Float(), nullable=False))
        batch_op.alter_column('total_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.drop_column('unit_price')

    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('margin_boss_total', sa.Float(), nullable=False))
        batch_op.drop_column('sale_type')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sale_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_column('margin_boss_total')

    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.alter_column('total_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.drop_column('unit_taxes')
        batch_op.drop_column('unit_purchase_price')

    with op.batch_alter_table('product_price_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_price_configs_id'))

    op.drop_table('product_price_configs')
    # ### end Alembic commands ###
