"""fix sevoil modeles colums

Revision ID: 51faf863364b
Revises: b7ec8ad6b018
Create Date: 2026-04-15 16:25:33.681862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51faf863364b'
down_revision: Union[str, None] = 'b7ec8ad6b018'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
