{
 "title": "Logging",
 "description": "Dashboard for visualizing logs from the Logging plugin",
 "tags": [
  "logs",
  "monitoring",
  "advanced-logging"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Total Log Events by Level",
   "type": "piechart",
   "description": "Total number of log events created via the advanced logging plugin, broken down by log level",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kaapi_advanced_logging_events_by_level) by (level)",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "Log Events Rate",
   "type": "timeseries",
   "description": "Rate of log events per minute",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(kaapi_advanced_logging_events_total[1m])",
     "legendFormat": "Log Events"
    }
   ]
  },
  {
   "title": "All Logs",
   "type": "logs",
   "description": "All logs from the Advanced Logging plugin",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{job=\"kaapi_advanced_logging\"}"
    }
   ]
  },
  {
   "title": "Error Logs",
   "type": "logs",
   "description": "Error logs from the Advanced Logging plugin",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{job=\"kaapi_advanced_logging\", level=\"error\"}"
    }
   ]
  },
  {
   "title": "Warning Logs",
   "type": "logs",
   "description": "Warning logs from the Advanced Logging plugin",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "targets": [
    {
     "expr": "{job=\"kaapi_advanced_logging\", level=\"warning\"}"
    }
   ]
  },
  {
   "title": "Info Logs",
   "type": "logs",
   "description": "Info logs from the Advanced Logging plugin",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "targets": [
    {
     "expr": "{job=\"kaapi_advanced_logging\", level=\"info\"}"
    }
   ]
  },
  {
   "title": "Log Levels Over Time",
   "type": "timeseries",
   "description": "Log levels over time",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum by(level) (count_over_time({plugin=\"advanced_logging\", level=~\"info|error|warning|debug\"} [5m]))",
     "legendFormat": "{{level}}"
    }
   ]
  }
 ]
}